### ISSUE TITLE
Add argvals support for peer

### ISSUE THREAD

**Issue by huangracer** [refunders/refund#29]
This should has impact on lpeer(), plot.peer() and plot.lpeer(). #9

**Comment by jgellar** [comment]
For the new `peer()` function, I made the default `argvals` be `1:ncol(X)`, which corresponds to previous versions of `peer()`. Should we leave it like this, or change it to `seq(0, 1, length=ncol(X))` like other `pfr` terms, e.g. `lf` and `af`?

**Comment by huangracer** [comment]
seq(0,1,length=ncol(X)) 

all default values for argvals in refund should be that

**Comment by jgellar** [comment]
Okay, done
