### ISSUE TITLE
Switch to roxygen2 documentation

### ISSUE THREAD

**Issue by fabian-s** [refunders/refund#3]

**Comment by mwmclean** [comment]
We should add R/refund-package.R file with some description of the package, too.

**Comment by mwmclean** [comment]
I will take care of this switch for the functions I've contributed to the package.

**Comment by fabian-s** [comment]
I'd have suggested pkg Rd2roxygen to get it done as automatically as possible. Should prob wait with this until after major re-constructive surgery on fosr etc has completed.

**Comment by mwmclean** [comment]
I knew something like that had to exist and yet I didn't bother to search for it.  Good to find typos in my documentation anyway.  I've already updated all my functions in my devel branch.

**Comment by fabian-s** [comment]
awesome, Matt!
