### ISSUE TITLE
PEER implementation in pfr()

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#38]
I realized I should be posting here instead of sending emails to 6 different people.

I implemented the svd step for `smooth.construct.peer.smooth.spec`, and it seems to be working - I basically figured this out by "guess and check". Both of the examples in the `peer()` help file seem to be working with their `pfr()` implementation. A few issues still remain:
1. Have to write the `peer()` wrapper and move the old code to `peer_old()`
2. Right now you have to supply the `X` matrix (the functional predictors) twice in the formula - once as the term you are taking a linear function of, and once in the `xt` list. I think this is unavoidable, but if we write the `peer()` wrapper referred to above, this can be done automatically (without the user having to do it).
3. I have allowed `k` to be specified, indicating the basis dimension. This is the number of columns of the `v` matrix from the svd that are retained. For example 2 in `peer()` (the simulated data), this works great, and I can get almost perfect estimation with a relatively low `k`. For example 1 (using the DTI data), lowering `k` from the full value (93, the number of columns of the `X` matrix) changes the estimate. I'm not sure why this is.
4. I'm not sure if I'm doing the right thing for the `rank` and `null.space.dimension`.
5. The model fits a lot slower than the old `peer()` implementation, 15 seconds vs. 0.75 seconds for example 1 from `peer()` on my laptop. Not sure why.

**Comment by fabian-s** [comment]
See https://gist.github.com/fabian-s/a566ddb5d8f5f17b4222 for example code.

TODOS:
- [ ] summary() doesn't work for the 2nd example
- [ ] fits are similar, but not exactly the same even with `fitter = "gamm"`: scaling of design matrix done in `gamm`?
- [ ] do more profiling to figure out run time differences

**Comment by jgellar** [comment]
Thanks for looking into this and for fixing up some of the `peer.smooth.spec` code. For those who hadn't seen, I wrote the `peer()` wrapper, and moved the old version to `peer_old`: Fabian's code references both of these functions. I built in checks to see if the old syntax is used to ensure backwards compatibility.

At ENAR earlier this week Phil, Rayman, and I talked about when the next refund release would be ready, and I think we decided we are almost there. Fabian, do you think you are going to have time to address the remaining issues you referenced? I could give it a look, but you are a lot more familiar with the inner-workings of `gam`/`lme` than I am. I'm surprised `summary()` doesn't work for that example, since it's just calling `summary.gam`. I think my biggest concern is the run time difference. When I plotted the fits on top of each other, I couldn't tell a difference visually, so I don't think identifying where the minor differences in fit come from is a big priority. The confidence intervals were quite a bit off, though.

Also, Fabian could you merge the `pfr-devel` branch in with the main `devel` branch? I'm still a little uncomfortable with github branching and don't want to be responsible for breaking the whole package.

**Comment by jgellar** [comment]
@fabian-s - could you take a look at the problem I marked on line 129 of `peer.R`? There is an issue related to passing a matrix as the `$xt` argument to `smooth.construct.peer.smooth.spec`. To see the problem, fit any of the examples under `?peer`, and then look at `fit$call`. Instead of using the name of the matrix in the call, it prints the entire matrix.

This isn't essential to fix, because the model is still fitting. It's just resulting in ugly outputs. I imagine the solution has something to do with a non-standard evaluation trick, something with `as.symbol`/`substitute`/`quote`/`parse` etc. But I tried a bunch of things and couldn't figure out a solution. 

`summary()` is also not working for fits with `peer()` terms - do you think this is essential to fix before the push to CRAN? `summary()` also isn't working for models with `re()` terms.
