### ISSUE TITLE
Down the line... fpca function?

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#40]
I don't think this wouldn't be implemented for the upcoming release, because it would take a little bit of work, but one thing I thought would be nice to have in `refund` would be an `fpca` function that returns a "fitted" `fpca` object, much like any regression function like `lm` or `pfr` does. The `fpca` function would have options to decide between different FPCA methods. The return object would basically just contain the PC's and the loadings for each subject in the original dataset, the mean function, and maybe a couple other things that depend on the method.

There would also be a `predict.fpca` method to make predictions for new functions. Right now the fit and predict steps are both combined in functions like `fpca.sc` and `fpca.face`, but I think it makes sense to separate them - that way if you just want to make predictions from an already-fitted fpca "model", you don't have to re-fit it. We could also write `plot` method that plots the first few PC's and/or a scree plot, and a `summary` method which maybe returns the PVE.

**Comment by fabian-s** [comment]
belongs in #34
