### ISSUE TITLE
fpca2s return object different from fpca.sc

### ISSUE THREAD

**Issue by fabian-s** [refunders/refund#43]
.. return object should look as much as possible like the one returned by fpca.sc

**Comment by jeff-goldsmith** [comment]
@fabian-s @lxiao16 

I think we addressed this when formatting output of fpca objects to interact well with refund.shiny. Can you confirm and close if it looks right to you?

**Comment by fabian-s** [comment]
looks good, i'm closing it. for future commits, note that you can simply write "closes #43" into the commit message and the issue will automatically be closed when you push it to the remote
