### ISSUE TITLE
Wrong documentation for fpca.face

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#46]
When roxygen documentation was added to `fpca.face`, somehow the `fpca.ssvd` documentation was added instead. None of the examples even call `fpca.face`, and the documentation is exactly the same as the `fpca.ssvd` documentation.

Matt, do you have time to re-do this?

**Comment by fabian-s** [comment]
@mwmclean are you alive?

**Comment by mwmclean** [comment]
Fixed by e708b5c0e604e1703f810792f44fb6079c0f20c6 and 7138c126f2f083caa713b7f403098deaa33f930b

**Comment by mwmclean** [comment]
Actually closed by 7138c126f2f083caa713b7f403098deaa33f930b
