### ISSUE TITLE
Plotting af terms with Qtransform option

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#47]
I have been playing around with the implementation of af terms on the pfr-devel branch. `af` has an option `Qtransform`, which does a time-specific quantile transformation of the X function, which is really useful. One thing I didn't like about this is that when you plot/extract the coefficient, it is still on the transformed scale. This makes it hard to interpret the coefficient on the original scale, especially because the quantile transformation is time-specific.

The `"dt"` basis that I wrote solves this problem, so I changed the `Qtransform` implementation to use this basis. The model fits exactly the same (same exact spline coefficients!), the difference is it makes the quantile transformation transparent so plotting/extracting the coefficient can be done on the original scale.

I would, however, like to make extracting/plotting on the transformed scale available. This ended up being a little trickier than I was hoping. I've been considering two strategies for this:
1. In `plot.pfr`, inject code (using `trace`) into `plot.mgcv.smooth`, which changes the coordinates to their transformed versions. This has to be done in `plot.mgcv.smooth` instead of `plot.gam`, because the grid isn't generated until `plot.mgcv.smooth`. The problem is that I don't know how to trace into an unexpected function without using `:::`, which we need to avoid.
2.  Do everything manually for these terms. This would be annoying.

Any ideas?

**Comment by jgellar** [comment]
I have a working version of this on `pfr-devel`. The only problem is that it uses `:::` to trace into `plot.mgcv.smooth`. I can think of two ways around this:
1. We overwrite `plot.mgcv.smooth` with our own local copy. I tried to do this (you can see this code commented out at the bottom of `plot.pfr.R`), but the problem was that `plot.gam` ends up calling `mgcv:::plot.mgcv.smooth` instead of our own `plot.mgcv.smooth`. Is there any way to get `plot.gam` to call our function instead? I was hoping to over-write `mgcv:::plot.mgcv.smooth`.
2. We ask Simon Wood if he could export `plot.mgcv.smooth`. Fabian, since I think you have a previous relationship with him, could you do that (if 1. above isn't an option)?

**Comment by jgellar** [comment]
My solution was to copy `plot.gam` and `plot.mgcv.smooth` into `refund` and make a couple edits.It's kind of cheating, but oh well. I documented both functions as copied from `mgcv`.

**Comment by fabian-s** [comment]
Thanks Jonathan. Seems like a good solution.

I take it we don't need to ask Simon to export these methods anymore since
we're using modified versions of them anyway now?

**Comment by jgellar** [comment]
Yeah, I guess not. We were going to have to have him export them and then use `trace`, but this is simpler.
