### ISSUE TITLE
pfr bug related to data environments and non-standard evaluation

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#49]
I got a chance to talk with Hadley WIckham today, and I asked him about the bug we were having a couple months back with the `testthat` tests - that the code would run fine when we ran it "manually", but the tests failed when we ran them as tests. He said that when this happens, it's usually in a model-building function, and it usually means that the author was not careful about the use of environments and non-standard evaluation.

This is something we should fix. I'll take a look when I get a chance, but I'm still pretty weak on these topics so I may need some help. I'd be afraid that any "solution" I come up with will be based on guess-and-check, and might not be robust (i.e., could cause another bug).

**Comment by fabian-s** [comment]
closing this since there was no further activity and described problems do not seem to be present currently.
