### ISSUE TITLE
Problem loading refund on my server?

### ISSUE THREAD

**Issue by jgellar** [refunders/refund#59]
I'm trying to load refund on my company's server, and getting an error:

```
> library(refund)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘graph’
In addition: Warning message:
package ‘refund’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘refund’
```

Does anyone know what this `graph` package is? It's not on CRAN, and isn't a direct dependency of `refund`. This may have something to do with the fact that the server is running a really old version of R (I've been trying to get them to update it for months, but they are slow):

```
> devtools::session_info()
Session info -----------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.98.1103)         
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            

Packages ---------------------------------------------------------------
 package    * version   date       source        
...
```

**Comment by fabian-s** [comment]
We rely on 2 Bioconductor packages until
https://github.com/refunders/refund/issues/57 is fixed.

For now, you'll need to run (http://www.bioconductor.org/install/)

source("https://bioconductor.org/biocLite.R")

biocLite(c("Rgraphviz", "graph"))

**Comment by jgellar** [comment]
Thanks Fabian. Why have I never had to do this (at least manually) before?

**Comment by fabian-s** [comment]
They used to be on CRAN as well until fairly recently, I guess...?
