### ISSUE TITLE
Bug in "vis.pfr"

### ISSUE THREAD

**Issue by aki-nishimura** [refunders/refund#61]
Matt (McLean) fixed a bug for me (in the "devel" branch) and now I seem to get another error.  Here is the code to reproduce the error. The code is identical to the help page of "vis.pfr" except that I add " ~ visit + sex + ."  

data(DTI)
DTI <- DTI[DTI$visit==1 & DTI$case==1 & complete.cases(DTI$cca),]
fit <- pfr(pasat ~ visit + sex + af(cca, basistype="te", k=c(8,8), m=list(c(2,3),c(2,3)), bs="ps"),
           method="GCV.Cp", gamma=1.2, data=DTI)
xval <- runif(1, min(fit$pfr$ft[[1]]$Xrange), max(fit$pfr$ft[[1]]$Xrange))
tval <- runif(1, min(fit$pfr$ft[[1]]$xind), max(fit$pfr$ft[[1]]$xind))
par(mfrow=c(2, 2))
vis.pfr(fit, deriv2=FALSE, xval=xval)
vis.pfr(fit, deriv2=FALSE, tval=tval)
vis.pfr(fit, deriv2=TRUE, xval=xval)
vis.pfr(fit, deriv2=TRUE, tval=tval)

**Comment by jgellar** [comment]
It looks like you're fitting a model with the variable `visit` in it, but `visit` has the same value (1) for every subject. Could this be the reason for the error?

I'm surprised the model even fits - how is this identifiable? Here is the parametric terms part of the model summary:

```
> summary(fit)
...
Parametric coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  22.1089     0.8118  27.236   <2e-16 ***
sexfemale    -0.2871     2.6348  -0.109    0.913    
visit        22.1089     0.8118  27.236   <2e-16 ***
---
```

So it looks like the "intercept" is getting split evenly between the actual intercept and the `visit` term.

**Comment by jgellar** [comment]
I fixed the bug, thanks Aki for pointing this out. Fix is currently in the devel branch.
