### ISSUE TITLE
refund failed check on CRAN

### ISSUE THREAD

**Issue by huangracer** [refunders/refund#69]
probably caused by the mgcv update

https://cran.r-project.org/web/checks/check_results_refund.html

**Comment by fabian-s** [comment]
@huangracer @philreiss : please check whether you think these changes are reasonable and if so migrate them to the devel branch (and CRAN, before they kick us off.....)

https://github.com/refunders/refund/commit/3743054848880e68918b012292e8a0d059e173d2?w=1
gives a better diff without any whitespace changes than using the link above.... (i removed all the damn tabs from the fosr code and replaced them by spaces, sorry.)

**Comment by huangracer** [comment]
Thank you very much @fabian-s . I rebased devel branch and submit it to CRAN.

**Comment by fabian-s** [comment]
Thanks @huangracer, you're the best!
