### ISSUE TITLE
Loading package causes segfault

### ISSUE THREAD

**Issue by samclifford** [refunders/refund#74]
Loading the CRAN version of the package, 0.1-16, on R 3.2.3 on OS X 10.12.2 causes a segfault

```
 *** caught segfault ***
address 0x318, cause 'memory not mapped'
```

Trying to install either the master or latest dev branch with devtools (refundDevel 0.1-17) gives a segfault and crashes both R and RStudio.

**Comment by fabian-s** [comment]
Closing this since refund does not include any C code that could trigger segfaults and we cannot reproduce the behavior on OS X machines.
