### ISSUE TITLE
lf() and missing values in the functional predictor

### ISSUE THREAD

**Issue by iclocher** [refunders/refund#79]
Hello,

I am using `pfr` and `lf` for a scalar-on-function regression. My functional data has some values missing completely at random and not at the end of the vector for each observation, so the missingness can't be resolved by using a variable domain.
The documentation for `lf` says the following about the first argument of the function:
 >  May include missing/sparse functions, which are indicated by NA values. 

It is the case of my functional data as you can see from the text file `funcdata1.txt` attached. However, when I run `FDAlin <- pfr(tfruits ~ lf(perf, k=nk, bs="ps")+log(tflowers), family=nb, data=LSdata)` , the summary of the model indicates that the number of observations read (51) is lower than the full dataset (64). The 13 observations missing correspond to observations with missing values. The code and two associated text files are attached.

@mwmclean and @fabian-s and @jgellar : In the example provided in the documentation for `lf`, the DTI1 object is being created but the NAs are removed with `complete.cases`. Why?
It seems that `lf` can't actually deal with a functional predictor containing missing values, contradicting the documentation. Is this true?

Thanks

[funcdata1.txt](https://github.com/refunders/refund/files/1361097/funcdata1.txt)
[scalardata.txt](https://github.com/refunders/refund/files/1361096/scalardata.txt)
[GitHub lf() can't have NAs.txt](https://github.com/refunders/refund/files/1361102/GitHub.lf.can.t.have.NAs.txt)

**Comment by mwmclean** [comment]
Did you try just removing that second line from the documentation, setting `DTI1 <- DTI` and seeing what happens when you run the different examples?

**Comment by iclocher** [comment]
@mwmclean Yes, I did.
When I use DTI instead of DTI1, the fitted models have a different number of fitted values: they seem to have either 334 or 340 fitted values (excluding fit4 that gives an error message regardless of the dataset used). When I use DTI1, all five models have 66 values. Therefore, in this example, the missingness doesn't seem to be a problem. **It is still unclear to me why using DTI1 instead of DTI was necessary to demonstrate the use of lf.**

Additionally and **as my provided code and data text files show, lf discards observations with missing values** when fitting the model, a feature I would like to avoid.
Do you have an idea as to why this is happening?

**Comment by iclocher** [comment]
I was able to appreciate the different presmoothing options available for `lf` from the refund documentation `create.prep.func`, which allowed me to interpolate individual trajectories even with some missing data, and thus use my complete dataset. 
Thank you for your answer.
