### ISSUE TITLE
fix fpca.sc for irregular data

### ISSUE THREAD

**Issue by fabian-s** [refunders/refund#8]
see Clara Happ's (clara.happ@stat.uni-muenchen.de) example & suggested patch @ https://gist.github.com/fabian-s/2ca8573f26fef8ccef8e
see also discussion in e-mail exchange re "eigenvalues in fpca2s" Sep. 2014

**Comment by philreiss** [comment]
This bug is just one of a number of examples in which using l2 (vector) rather than L2 (functional) inner products can cause problems. I'm working to modify fpca.sc, using Clara's fix as a starting point. Functional-predictor regression functions will need to be modified too. This issue is related to #9.

**Comment by huangracer** [comment]
Need to check when the current progress is documented. @philreiss

**Comment by jeff-goldsmith** [comment]
In updating ccb.fpc, I found that the example using fpca.sc for sparse data no longer performs well. It seems that curve-specific scores are over-shrunk towards the mean -- this is pretty obvious if you look at the results of the example analysis, which are very different from previous versions of ccb.fpc and from the paper that the function is based on. 

Is the problem of over-shrinking scores related to this issue, or should it be a separate one?

**Comment by fabian-s** [comment]
```
#devtools::load_all() ## refundDevel!
set.seed(2015050503)


ranfun <- function(t, npc = 3, sd.eps = .1) {
  drop(poly(t, degree = npc) %*% rnorm(npc, sd=npc:1) + rnorm(length(t), sd=sd.eps))
}  
n <- 100
G <- 80
## range of argvals does not seem to matter for results below:
t <- seq(0, 1, l=G)#1:G  
npc <- 3
Y <- t(replicate(n, ranfun(t, npc = npc)))
Y10 <- {
  tmp <- Y
  tmp[cbind(rep(1:n, e = .1*G), as.vector(replicate(n, sample(1:G, .1*G))))] <- NA
  tmp
}
Y50 <- {
  tmp <- Y
  tmp[cbind(rep(1:n, e = .5*G), as.vector(replicate(n, sample(1:G, .5*G))))] <- NA
  tmp
}
Y80 <- {
  tmp <- Y
  tmp[cbind(rep(1:n, e = .8*G), as.vector(replicate(n, sample(1:G, .8*G))))] <- NA
  tmp
}
Y95 <- {
  tmp <- Y
  tmp[cbind(rep(1:n, e = .95*G), as.vector(replicate(n, sample(1:G, .95*G))))] <- NA
  tmp
}

fpc <- list("0" = fpca.sc(Y, argvals = t, npc = npc),
  "10"= fpca.sc(Y10, argvals = t, npc = npc),
  "50"= fpca.sc(Y50, argvals = t, npc = npc),
  "80"= fpca.sc(Y80, argvals = t, npc = npc),
  "95"= fpca.sc(Y95, argvals = t, npc = npc))
scores <- do.call(cbind, lapply(fpc, function(x) as.vector(x$scores)))
values <- do.call(cbind, lapply(fpc, function(x) as.vector(x$evalues)))
panelf <- function(x,y,...){ 
  points(x, y, ..., pch = 19, col = rgb(0, 0, 0, 1/sqrt(length(x))))
  abline(c(0, 1)); abline(c(0, -1)) #show both because of possible fpc sign change
}
pairs(values, asp = 1, panel = panelf, ylim = range(values), xlim = range(values))
## -> eigenvalues estimated quite well for up to 80% missing
```

![image](https://cloud.githubusercontent.com/assets/998541/7469096/fd5ee750-f30f-11e4-8483-1d6c7a398aa8.png)

```
pairs(scores, asp = 1, panel = panelf, ylim = range(scores), xlim = range(scores))
## -> overshrinkage of scores for sparse data with > 50% missing
## does not improve all that much for larger G (?!?)
```

![image](https://cloud.githubusercontent.com/assets/998541/7469103/12b01430-f310-11e4-9ee0-14b4ca03205f.png)

Seems to me like this is unrelated to the issue of using vector norms versus function norms as the overshrinkage remains the same regardless of how  `argvals` is supplied.

Might this not just be an unavoidable consequence of ridge-estimating the scores? I.e., whenever there are few datapoints for a given curve, the Gaussian prior on the scores for that curve has more impact and shrinks them towards 0 more strongly? One way to find out would be to modify the script above so curves in the same data set have varying amounts of missings and check that curves with lots of missings tend to get scores that are shrunk more strongly than curves with fewer missings. A counter point to that would be that increasing the grid density `G`  to 500 in the script above didn't change the pattern at all, but made it even clearer.... 

@jeff-goldsmith Jeff, any idea what has changed in fpca.sc to cause the difference in results? 
did we ever not do ridge-estimates for the scores but simple OLS estimates?

another rabbit hole....

**Comment by jeff-goldsmith** [comment]
Just to put a concrete example of the issue I'm talking about:

``` r
## Not run: 
data(cd4)

# obtain a subsample of the data with 25 subjects
set.seed(1236)
sample = sample(1:dim(cd4)[1], 25)
Y.sub = cd4[sample,]

# obtain a mixed-model based FPCA decomposition
library(refund)
Fit.MM.old = fpca.sc(Y.sub)
detach("package:refund", unload=TRUE)

library(refundDevel)
Fit.MM.new = fpca.sc(Y.sub)
detach("package:refundDevel", unload=TRUE)


# plot fitted values
EX = 2

par(mfrow = c(1,2))


plot(Fit.MM.old$Yhat[EX,], type = 'l', ylim = c(500, 3000))
points(Y.sub[EX,], pch = 19, col = 2)

plot(Fit.MM.new$Yhat[EX,], type = 'l', ylim = c(500, 3000))
points(Y.sub[EX,], pch = 19, col = 2)
```

![example](https://cloud.githubusercontent.com/assets/8386439/7472263/ae23fb00-f2fe-11e4-98bb-fa5f498bbb23.png)

@fabian-s I don't think the issue is the ridge regression part -- as far as I can tell, the code for estimating scores is the same in both the `refund` and `refundDevel` versions of `fpca.sc` (that code snippet is below for reference). I haven't had a chance to think more carefully but my current guess is that the `argvals` should show up in the score estimation in the new version, which seems to still be using vector products. Maybe we updated the first have of the function to use `argvals` but not the second half?

``` r
for (i.subj in 1:I.pred) {
  obs.points = which(!is.na(Y.pred[i.subj, ]))
  if (sigma2 == 0 & length(obs.points) < npc) 
    stop("Measurement error estimated to be zero and there are fewer observed points than PCs; scores cannot be estimated.")
  Zcur = matrix(Z[obs.points, ], nrow = length(obs.points), 
                ncol = dim(Z)[2])
  ZtZ_sD.inv = solve(crossprod(Zcur) + sigma2 * D.inv)
  scores[i.subj, ] = ZtZ_sD.inv %*% t(Zcur) %*% (Y.tilde[i.subj, 
                                                         obs.points])
  Yhat[i.subj, ] = t(as.matrix(mu)) + scores[i.subj, ] %*% 
    t(efunctions)
  if (var) {
    ...
    }
  }
}
```

**Comment by fabian-s** [comment]
Commit https://github.com/refunders/refund/commit/a820127b69a60c69a4800524010bc3ec0b27ddfe gets rid of most of these issues I think. The estimate for the error variance was wrong.

@jeff-goldsmith works for your cd4 example for me now
@philreiss i  reverted one of your changes to fpca.sc (see diff for the referenced commit) because it led to dramatic overestimates of the error variance. this was very try-and-error, though.... might not be perfect.

**Comment by jeff-goldsmith** [comment]
Yeah, that seems to fix the problem. 

@fabian-s One minor thing I just addressed -- your commit got rid of `ZtZ_sD.inv`, but this is used when `var == TRUE` on line 297. I reverted that to the previous version in commit 0074759b65470482e190ae3023d63ba6ea6e0a17.
