### ISSUE TITLE
pffr breaks with default algorithm (bam) and ffpc terms

### ISSUE THREAD

**Issue by ARLundborg** [refunders/refund#94]
I have the following data:

https://gist.github.com/ARLundborg/7657d0bb8ea84c7190daa55a8a069e8e

and am attempting to run the following:
```r
library(refund)
X <- as.matrix(unname(read.csv("pffr_ffpc_break_X.csv")))
Y <- as.matrix(unname(read.csv("pffr_ffpc_break_Y.csv")))

m <- pffr(Y ~ ffpc(X))
```
This yields an error:
```r
Error in if (sum(ind) == n) { : missing value where TRUE/FALSE needed
```
and a large traceback. If I do `m <- pffr(Y ~ ffpc(X), algorithm="gam")`, however, the code runs without failure (but is fairly slow). Am I doing something wrong here or is there a bug somewhere in code? 

EDIT: I get the same error if I let X and Y be random Brownian noise with the same dimensions (268 curves observed at an equidistant grid of length 571).

**Comment by fabian-s** [comment]
Seems like the way we set the `chunk.size` argument for `bam` is broken -- please set it manually in the mean time, the code below works for me:

```r
url <- "https://gist.githubusercontent.com/ARLundborg/7657d0bb8ea84c7190daa55a8a069e8e/raw/42947d49620e49af0d8afa082e9b15d0718e4081/pffr_ffpc_break_X.csv"
X <- as.matrix(unname(read.csv(url)))
Y <- as.matrix(unname(read.csv(url))) #does not make sense, ok for testing to set X == Y

m <- pffr(Y ~ ffpc(X), chunk.size = 31000)
```
For you too?

Thanks for the report @ARLundborg

**Comment by ARLundborg** [comment]
That works! Thanks a lot for the swift response!
